export const AceOfShadowsConfig = {
  designWidth: 600,
  designHeight: 100,
  totalCards: 144,
  stackOffsetY: -1.5,
  cardScale: 0.35,
  responsiveScaleBreakpointWidth: 1200,
  responsiveScaleBreakpointHeight: 720,
  tweenDurationMs: 2000,
  launchIntervalMs: 1000,
  startXRatio: 7 / 10,
  endXRatio: 3 / 10,
  centerYRatio: 1 / 2,
  arcLiftY: 75,
  easing: {
    midpoint: 0.5,
    initialMultiplier: 4,
    endScale: 2,
    power: 3,
    endDivisor: 2,
  },
} as const;